course = "python programming"
print(len(course))
print(course[:3])
print(course[0:])
print(course[0:9])
print(course.upper())
print(course.lower())
print(course.title())
print("pro" in course)
print(course.find("pro"))
print(course.replace("p", "j"))
print("swift" not in course)
